### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Flordy** [multimokia/MAS-Submod-Auto-Atmos-Change#14]
Hi, when i enter my city. Monika did not find any. But still proceed. I just realize that I type the spelling of my city wrong and my question is that is it possible for monika to ask my location again??

**Comment by multimokia** [comment]
You can indeed change it, visit `Hey Monika... > You > [Player]'s Location`

**Comment by sman20222** [comment]
I tried doing this myself, since Monika doesn't recognize my city, and for some reason the option for changing my location does not appear under `Hey Monika... > You > My Location`

Am I supposed to reach a certain level of affection before I am allowed to change this? Or is this just a bug? Thanks.

**Comment by multimokia** [comment]
Mmmm, that's odd, it should have just directly unlocked?
